lenguage: node_js
cache:
    directories:
        - node_modules
        - ~/.npm
node_js:
    - '12'
git:
    depth: 3
script:
    - yarn test
notifications:
    email:
        reciepients:
            - luisalbertodev@gmail.com
        on_success: always
        on_failure: always
deploy:
    provider: heroku
    skip-cleanup: true
    keep-history: true
    api-key: a3714032-4f9e-4ef6-8b96-ce1cc23272fe
    app: platzi-travis-ci
    on:
        repo: luisalbertodev/platzi-store-backend
